[tool.poetry]
name = "alien-invasion"
version = "0.1.0"
description = ""
authors = ["Bijay Upreti <bjupreti123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
